### ISSUE TITLE
Mac Mouse Fix does not capture any mouse events on macOS 13 Ventura [bug]

### ISSUE THREAD

**Issue by lrcf** [noah-nuebling/Mac-Mouse-Fix#297]
# Update: [New beta was released](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.2.1-Beta-1)

---

## Description

After upgrading to macOS Ventura, the app nor the Helper can capture any mouse events. I’ve tried both registered and unregistered events, nor is it possible to register a new event.

Console.app does not show any logs related to that, I’ve not checked any other logs yet.

## Steps to reproduce

1. Upgrade from macOS Monterey to Ventura using the Beta Software Program
2. Press any mouse button other than the default ones (left and right click)

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: 13.0 beta 1
Mouse Model: MX Vertical, although this is probably not relevant

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by chamburr** [comment]
Also suffering from Mac Mouse Fix not working. It appears to me that `IOHIDDeviceRegisterInputValueCallback` is not working, no events are received. Hopefully we can get a fix soon!

**Comment by lrcf** [comment]
> It appears to me that `IOHIDDeviceRegisterInputValueCallback` is not working, no events are received. Hopefully we can get a fix soon!

Good catch! Did you file a radar?

**Comment by chamburr** [comment]
> Good catch! Did you file a radar?

Yep, already did.

**Comment by tolgaaaltas** [comment]
I guess we won't get an update in the short term.

**Comment by lrcf** [comment]
> I guess we won't get an update in the short term.

If the convenience of having those side buttons working is important to you right now (and you are willing to sacrifice some customisability), there are other paid applications that work with macOS Ventura right now.

However, it’d be nice to see this issue get fixed here.

**Comment by tolgaaaltas** [comment]
> > I guess we won't get an update in the short term.
> 
> If the convenience of having those side buttons working is important to you right now (and you are willing to sacrifice some customisability), there are other paid applications that work with macOS Ventura right now.
> 
> However, it’d be nice to see this issue get fixed here.

Could you suggest to me a few paid applications? I really don't know the alternatives.

**Comment by lrcf** [comment]
> Could you suggest to me a few paid applications? I really don't know the alternatives.

* [BetterTouchTool](https://folivora.ai/) — `brew install --cask bettertouchtool` — $9/2yr | $21 for ‘lifetime’
  * This one is not as simple as MacMouseFix or BetterMouse.
* [BetterMouse](https://better-mouse.com/) — `brew install --cask bettermouse` — $5
* ~~[Karabiner Elements](https://karabiner-elements.pqrs.org/)~~ may crash the system — pqrs-org/Karabiner-Elements#3108

**Comment by chamburr** [comment]
Hey, I made a temporary fix which you can download here. [Mac Mouse Fix](https://github.com/noah-nuebling/mac-mouse-fix/files/8905476/Mac.Mouse.Fix.app.zip)

You need to run `xattr -d com.apple.quarantine /Applications/Mac\ Mouse\ Fix.app` as it is not signed. You also need to manually give `/Applications/Mac Mouse Fix.app/Contents/Library/LoginItems/Mac Mouse Fix Helper.app` the Accessibility and Input Monitoring permissions.

Let me know if this works.

**Comment by tolgaaaltas** [comment]
Hey @chamburr,
It's working, thank you! :)

**Comment by lrcf** [comment]
@chamburr Thanks for the fix! Have you thought of filing a pull request? It’d be nice to get your fix merged into the upstream.

**Comment by jdbool** [comment]
@chamburr The app is saying to grant permissions despite Mac Mouse Fix and Mac Mouse Fix Helper both having Accessibility and Input Monitoring permissions.

**Comment by chamburr** [comment]
> @chamburr Thanks for the fix! Have you thought of filing a pull request? It’d be nice to get your fix merged into the upstream.

Considering it is not a complete fix, I would not open a pull request. The issue is that IOHIDDeviceOpen needs to be called before IOHIDDeviceRegisterInputValueCallback. However, the input monitoring permission is needed for IOHIDDeviceOpen, and I'm not sure how to add the permission check into the code.

**Comment by chamburr** [comment]
> @chamburr The app is saying to grant permissions despite Mac Mouse Fix and Mac Mouse Fix Helper both having Accessibility and Input Monitoring permissions.

I found the new System Settings buggy when dealing with permissions. Maybe you can try using [System Preferences](https://github.com/noah-nuebling/mac-mouse-fix/files/8925427/System.Preferences.app.zip) and re-grant the permissions. You need to allow running in security settings when opening for the first time.

**Comment by krackers** [comment]
Question: why does the app intercept the side-button events at the IOKit level (via `IOHIDDeviceRegisterInputValueCallback`) instead of doing this at the quartz level (via `CGEventTap`)?

**Comment by noah-nuebling** [comment]
Hi guys, thanks for contributing! And thanks @chamburr for posting a fix!

I'd suggest we just use his fix for now.  I strongly expect Apple will fix `IOHIDDeviceRegisterInputValueCallback()` before Ventura 1.0 which should make the official Mac Mouse Fix release work correctly again. 
If Apple don’t fix it , I'm very open to merging @chamburr's fix.

I hope that makes sense for everyone! Let me know if there’s something else I should consider. 

## The details

Here's an **overview** of my understanding of the issue:

- Currently, Mac Mouse Fix uses the Apple API function `IOHIDDeviceRegisterInputValueCallback()` to determine which device a CGEvent stems from. According to @chamburr this function is currently broken which also breaks Mac Mouse Fix. I expect that what the fix essentially does is disable this mechanism for determining which device sent an event - thereby removing the dependence on the broken `IOHIDDeviceRegisterInputValueCallback()`
- Currently, determining which device sent an event is not essential, so the app will still work fine. I think the only thing it is used for is filtering button events from Apple Devices. But since the app doesn't allow remapping to left click and right click anyways, and any Apple devices I can think of only have left click and right click, this doesn't make a difference.
- Some of the state management code (tracking long clicks, double clicks, etc) saves separate state per device. But if you don't use several mice at the same time on the same computer - which I don't expect anyone does - this shouldn't be an issue either.
- → So if I understand correctly, the fix would break some internal mechanisms, but that shouldn't make a practical difference to anyone.

However I still think it makes sense to **leave the current mechanism in place** for the following reasons:

- I do expect to to use the ability to determince which device sent a CGEvent for more things in the future. I'm not sure if I ever want to build completely device specific settings, but we'd definitely need it for that. I definitely want to support device-specific features like tilting scroll wheels and gesture buttons at some point though. And I expect to use it for that, as well. 
- I expect Apple to fix `IOHIDDeviceRegisterInputValueCallback()` eventually, before Ventura releases, making the current mechanism work again.

I can think of some arguments for **throwing away the current mechanism**, but I don't think they hold up:

- I found some hacky ways to extract a driver-level event (IOHIDEvent) from a CGEvent. These events contain lots of extra data, including which device sent them! This seems to be a much superior way to solve the problem. Expecially for determining the sender of a scroll events there were some issues with the old mechanism.
    -> However, since I haven't done much testing on this, I'm not entirely sure that this will work correctly. So I'm uncomfortable throwing the existing mechanism away in favor of it.
- It would make the app usable for Ventura Beta users
    → However, they can just use @chamburr's fix for now. I don't think it makes sense to have a whole new release to work around an Apple API being broken in a Beta

**Comment by krackers** [comment]
@noah-nuebling Thanks for the info! Could you elaborate more on ` extract a driver-level event (IOHIDEvent) from a CGEvent` – I assume you basically reverse-engineered the struct layout for `CGEvent`? While I agree that this may be prone to breakage, I've always wanted the ability to get access to the underlying IOHIDEvent, so I'd appreciate if you could jot down your notes into a gist or something.

**Comment by noah-nuebling** [comment]
Hey @krackers, the code for extracting `IOHIDEvents` from `CGEvents` is already working in the `version-3` branch of this repo. You can find that code and a detailed explanation of how I arrived at it in the `CGEventHIDEventBridge` class. 

When you call `[hidEvent description]` it will dump all of it's datafields in a totally structured way with all the data fields labeled. You can also read and write to these data fields using simple ObjC property syntax. E.g. `hidEvent.deltaY = 24.6` It's really quite cool! And I even wrote a function `HIDEventGetSendingDevice(hidEvent)` that will get you the `IOHIDDeviceRef` for the sender of the event.

Here you can see the output that the `Scroll` class generates by calling `[hidEvent description]` and `HIDEventGetSendingDevice(hidEvent)` on an incoming scroll event:

```
2022-06-24 15:41:04.243492+0200 Mac Mouse Fix Helper[23930:903439] Scroll event: +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Timestamp:           1864058155481
Total Latency:       773 us
SenderID:            0x000000010000A1F3
BuiltIn:             0
ValueType:           Relative
EventType:           Scroll
Flags:               0x0
X:                   0.000000
Y:                   -1.000000
Z:                   0.000000
ChildEvents:        
    -----------------------------------------------------------------------
    ValueType:           Relative
    EventType:           Scroll
    Flags:               0x10000
    X:                   0.000000
    Y:                   -0.001633
    Z:                   0.000000
    -----------------------------------------------------------------------
    -----------------------------------------------------------------------
    ValueType:           Absolute
    EventType:           VendorDefined
    Flags:               0x1
    UsagePage:           65280
    Usage:               24
    Version:             0
    DataLength:          124
    Data:                16 00 00 00 00 00 00 00 00 00 00 00 d9 31 86 02 b2 01 00 00 00 00 00 00 00 00 00 00 f3 a1 00 00 01 00 00 00 00 00 00 00 ff ff 00 00 00 00 00 00 66 e6 ff ff 00 00 00 00 00 00 00 00 ff ff ff ff 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f3 a1 00 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
    -----------------------------------------------------------------------
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2022-06-24 15:41:04.244294+0200 Mac Mouse Fix Helper[23930:903439] Device sending scroll: Logitech M720 Triathlon
```

That's so cool right?! 

I even created a `CGEventSetHIDEvent(cgEvent, hidEvent)` function that you can use to create `CGEvents` from `HIDEvents`. I haven't tested if it works yet, but if it does that would open so many doors!!

Hope that is helpful! Let me know if you have any further questions.

**Comment by chamburr** [comment]
> The issue is that IOHIDDeviceOpen needs to be called before IOHIDDeviceRegisterInputValueCallback. However, the input monitoring permission is needed for IOHIDDeviceOpen, and I'm not sure how to add the permission check into the code.

Hey @noah-nuebling, thanks for the detailed explanation. I wanted to clarify that the latest status of the issue is quoted above. The fix involves opening the device, not replacing the IOHIDDevice logic. The callback function seems to fully work after opening the device (and enabling permission).

However, I could not find any documentation on this change, so I'm not sure if it's even an intended behaviour. I only found the issue when comparing with another piece of working code from a different app.

**Comment by davidzech** [comment]
I would open a radar to get clarity on whether the behavior in Monterey or Ventura is correct.

**Comment by jdbool** [comment]
> > @chamburr The app is saying to grant permissions despite Mac Mouse Fix and Mac Mouse Fix Helper both having Accessibility and Input Monitoring permissions.
> 
> I found the new System Settings buggy when dealing with permissions. Maybe you can try using [System Preferences](https://github.com/noah-nuebling/mac-mouse-fix/files/8925427/System.Preferences.app.zip) and re-grant the permissions. You need to allow running in security settings when opening for the first time.

Thanks, but that doesn't work -- 'The application "System Preferences" can't be opened.'

**Comment by tolgaaaltas** [comment]
The official stable version or @chamburr's fix doesn't work on beta 3.

**Comment by arm64eabi** [comment]
on beta 2 the gestures were not working but the separating natural scrolling behavior for mouse/trackpad was working. Now in beta 3, it is also not working.

**Comment by jfdnet** [comment]
> > > I guess we won't get an update in the short term.
> > 
> > 
> > If the convenience of having those side buttons working is important to you right now (and you are willing to sacrifice some customisability), there are other paid applications that work with macOS Ventura right now.
> > However, it’d be nice to see this issue get fixed here.
> 
> Could you suggest to me a few paid applications? I really don't know the alternatives.

I am using scroll reverser now

**Comment by nick-s5** [comment]
> The official stable version or @chamburr's fix doesn't work on beta 3.

Same here. "Enable Mac Mouse Fix" checkbox can't be checked.

**Comment by jfdnet** [comment]
> > The official stable version or @chamburr's fix doesn't work on beta 3.
> 
> Same here. "Enable Mac Mouse Fix" checkbox can't be checked.

OH I just found macOS 13 can disable natural scrolling for the mouse in setting.

**Comment by noah-nuebling** [comment]
Hey guys, I just published a [new beta version](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.2.1-Beta-1) that should work great on Ventura!

Let me know how it works.

**Comment by noah-nuebling** [comment]
Oh and @chamburr – let me know how you would like to be credited at noah.n.developer@gmail.com.

**Comment by chamburr** [comment]
Thanks for the fix! It works perfectly on Ventura beta 4.

For credit, the mention on the release page is sufficient - I appreciate that.

**Comment by LinusGeffarth** [comment]
awesome, it works on Ventura now. love this app so much, it's a must-have! thanks so much for making & maintaining this 🙏

**Comment by fnschmidt** [comment]
Unfortunately still broken for me. Running newest Ventura 22A5331f, and the same setup works in Monterey.

I can enable Mac Mouse Fix, but only smooth scrolling works. MMF does not recognize any button: no gestures work and adding new key mappings also doesn’t work, it  registers no keypress (apart from button 1 or 2).

i‘m using a USB dongle and wireless mouse (Katar Pro Wireless). I have no other mice to test and the bluetooth mode is incompatible with Ventura

**Comment by noah-nuebling** [comment]
Hey greybaron, I don't know what might be causing that. Here are some ideas that could help us figure this out:

1. Turn off MMF and see if [this online mouse test](https://www.onlinemictest.com/mouse-test/) works
2. Try a different mouse with MMF if you get the chance to
3. Try your mouse with some other mouse software like SteerMouse
4. See if you're running some other mouse software that might be interfering with MMF
5. File a [Bug Report](https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=bug-report) and attach some Console Logs

Let me know if you find anything!

**Comment by fnschmidt** [comment]
Hi Noah.
1. The online test detects all buttons
2. I will when I get the chance
3. SteerMouse detects all buttons
4. I was running Karabiner-Elements, but disabling it and rebooting didn't make a difference; also I disabled 'modify events' for my mouse. 

I have created a new issue #362. There are a few error messages in the log that seem relevant.
